server:
  port: 8070
spring:
  datasource:
    username: mangix
    password: mangix123456
    url: jdbc:mysql://127.0.0.1:3306/mangix?useUnicode=true&characterEncoding=utf-8&serverTimeZone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10000Mb
      max-request-size: 100000Mb
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yunqiic.mangixuploader.model
upload:
  path: ./upload/