version: '3'
services:
  mangix:
    build:
      context: mangix-fe
      dockerfile: Dockerfile
    container_name: mangix-fe
    ports:
      - "8070:8070"
    volumes:
      - ./mangix/upload:/home/mangix/upload
      - /etc/localtime:/etc/localtime
    restart: always