version: '3'
services:
  mangix-mysql80:
    image: mysql:8.0
    container_name: mangix-mysql
    ports:
      - "3306:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/init-sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mangix123456
    restart: always
  mangix:
    build:
      context: mangix-fe
      dockerfile: Dockerfile
    container_name: mangix-api
    ports:
      - "8070:8070"
    volumes:
      - ./mangix/upload:/home/mangix/upload
      - /etc/localtime:/etc/localtime
    depends_on:
      - mangix-mysql80
    restart: always